apiVersion: apps/v1
kind: Deployment
metadata:
  # name: nginx-deployment
  name: nginx
  labels: #add
    app: nginx #add
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        env:
        - name: SSH_USER
          value: adminssh
        - name: SSH_PASSWORD
          value: adminssh
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  # labels: #add
    # app: nginx #add
  annotations:
    # metallb.universe.tf/address-pool: nginx-ip
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  # loadBalancerIP: 172.17.0.2
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  - port: 22
    name: ssh
    targetPort: 22