apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: ip_nginx
      protocol: layer2
      addresses:
      - 172.18.1.2-172.18.1.2
    - name: ip_ftps
      protocol: layer2
      addresses:
      - 172.18.1.3-172.18.1.3
    - name: ip_php
      protocol: layer2
      addresses:
      - 172.18.1.4-172.18.1.4