apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftp
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv-min
      protocol: TCP
      port: 21009
      targetPort: 21009
    - name: pasv-mid
      protocol: TCP
      port: 21010
      targetPort: 21010
    - name: pasv-max
      protocol: TCP
      port: 21011
      targetPort: 21011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: img_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp
        - containerPort: 21
          name: ftps
        - containerPort: 21009
          name: pasv-min
        - containerPort: 21010
          name: pasv-mid
        - containerPort: 21011
          name: pasv-max