apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  ports:
    - name: ftps
      port: 21
      protocol: TCP
      targetPort: 21
  selector:
    app: ftps
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - image: img_ftps
          imagePullPolicy: Never
          securityContext:
            privileged: true
          name: ftps
          ports:
            - name : ftps
              containerPort: 21
#          livenessProbe:
#            exec:
#              command:
#              - pgrep "vsftpd"