apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  -  name: ftp-data
     port: 20
  -  name: ftp-connection
     port: 21
  -  name: pftp-data-0
     port: 21000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: img_ftps
        imagePullPolicy: Never
        env:
        - name: FTPS_USER
          value: ftps_admin
        - name: FTPS_PASSWORD
          value: ftps_admin
        ports:
        - containerPort: 21
        - containerPort: 20
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /var/ftp
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
