apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
    tier: frontend
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: img_grafana
          imagePullPolicy: Never
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            exec:
              command:
                - pgrep "grafana"
            initialDelaySeconds: 10
            periodSeconds: 10