apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
  - name: http
    port: 8086
    targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: img_influx
        imagePullPolicy: Never
        securityContext:
          privileged: true
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-pv-storage
          mountPath: /root/.influxdb/
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - 'echo "show databases" | influx'
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: influxdb-pv-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
