apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.0.2-172.17.0.2
    # - name: nginx-ip
    #   protocol: layer2
    #   addresses:
    #   - 172.17.0.2-172.17.0.21
    