apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  labels:
    app: wordpress
spec:
  ports:
    - port: 5050
      targetPort: 5050
      name: wordpress
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: img_wp
        imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 5050
          name: wordpress
        livenessProbe:
          exec:
            command:
              - curl
              - -I
              - http://localhost:5050
          initialDelaySeconds: 10
          periodSeconds: 10